# Generated by Django 5.1.3 on 2024-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(default='Unknown Artist', max_length=255)),
                ('audio', models.FileField(upload_to='songs/')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
            ],
            options={
                'db_table': 'Card',
            },
        ),
    ]
